# Generated by Django 4.0.3 on 2022-04-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='EndingTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='startingTime',
            field=models.DateTimeField(),
        ),
    ]
