# Generated by Django 4.0.3 on 2022-06-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
