# Generated by Django 4.0.3 on 2022-06-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
