# Generated by Django 4.0.3 on 2022-04-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='ststus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/product'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='media/productImages'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profilePicture',
            field=models.ImageField(upload_to='media/profile'),
        ),
    ]
