# Generated by Django 4.0.3 on 2022-04-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bid_ststus_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='ststus',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
