# Generated by Django 4.0.3 on 2022-04-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bid_ststus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='ststus',
            new_name='status',
        ),
    ]
