# Generated by Django 4.0.3 on 2022-05-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_payment_amount_alter_payment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentId',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
