# Generated by Django 4.0.3 on 2022-06-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_payment_amount_alter_payment_paymentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
